language: objective-c
os: osx
osx_image: xcode11.7
branches:
  only:
    - master
    - /^v?[0-9]+\.[0-9]+\.[0-9]+(-.*)?$/
cache:
  directories:
  - vendor/bundle
  
install:
  - bundle config set path 'vendor/bundle'
  - travis_wait bundle install

jobs:
  include:
    - stage: release
      env: CocoaPods
      script:
        - bundle exec pod setup 
        - bundle exec pod lib lint --allow-warnings
      deploy:
        provider: script
        cleanup: true
        script: bundle exec pod trunk push ParseLiveQuery.podspec --allow-warnings
        on:
          tags: true
          all_branches: true
    - stage: release
      env: Docs
      script:
        - ./jazzy.sh
      deploy:
        provider: pages
        strategy: git
        cleanup: true
        token: $GITHUB_TOKEN
        local_dir: ./docs/
        on:
          tags: true
          all_branches: true
