branches:
  only:
    - master
    - /^v?[0-9]+\.[0-9]+\.[0-9]+(-.*)?$/
language: objective-c
os: osx
osx_image: xcode11
cache:
  - cocoapods
before_install:
  - git submodule update --init --recursive
install:  bundle install

jobs:
  include:
    - stage: distribution
      env: CocoaPods
      script: EXPANDED_CODE_SIGN_IDENTITY="-" EXPANDED_CODE_SIGN_IDENTITY_NAME="-" bundle exec pod lib lint --allow-warnings
      deploy:
        provider: script
        skip_cleanup: true
        script: ./publish.sh
        on:
          tags: true
          all_branches: true
    - stage: distribution
      env: Docs
      script: bundle exec jazzy
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
        local_dir: docs/
        on:
          all_branches: true
