language: objective-c
os: osx
osx_image: xcode11.2
branches:
  only:
    - master
    - /^v?[0-9]+\.[0-9]+\.[0-9]+(-.*)?$/
cache:
  directories:
    - vendor/bundle
  
install:
  - bundle config set path 'vendor/bundle'
  - travis_wait bundle install

jobs:
  include:
    - stage: release
      env: CocoaPods
      script: bundle exec pod lib lint --allow-warnings
      deploy:
        provider: script
        cleanup: false
        script: bundle exec pod trunk push ParseLiveQuery.podspec --allow-warnings
        on:
          tags: true
          all_branches: true
    - stage: release
      env: Docs
      script: bundle exec jazzy
      deploy:
        provider: pages
        cleanup: false
        github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
        local_dir: docs/
        on:
          tags: true
          all_branches: true
